# Generated by Django 4.1.5 on 2023-09-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_regnum',
            field=models.CharField(max_length=33, null=True, verbose_name='사업자등록번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hp',
            field=models.CharField(max_length=11, null=True, verbose_name='휴대폰번호'),
        ),
    ]
