# Generated by Django 4.1.7 on 2023-05-04 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paesu_record',
            name='user_id_p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='아이디'),
        ),
        migrations.AddConstraint(
            model_name='paesu_record',
            constraint=models.UniqueConstraint(fields=('date', 'date_ck'), name='유저 기록 unique key'),
        ),
    ]
